<?php
/**
 * @file
 * Code for the Open Berkeley Admin feature.
 */

include_once 'openberkeley_admin.features.inc';
/**
 * Implements hook_menu().
 */
function openberkeley_admin_menu() {

  $items = array();

  $items['admin/config/openberkeley'] = array(
    'title' => 'Open Berkeley',
    'description' => 'Configure Open Berkeley settings.',
    'position' => 'left',
    'weight' => -20,
    'page callback' => 'system_admin_menu_block_page',
    'access callback' => TRUE,
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  return $items;
}

/**
 * Implementation of hook_form_alter
 *
 */
function openberkeley_admin_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case "views_form_control_users_page_1":
      if (!isset($form['add_roles']) || (!isset($form['remove_roles']))) {
        break;
      }
      $admin_rid = variable_get('user_admin_role');
      $roles = user_roles();
      $admin_rolename = NULL;
      if ((!is_array($roles)) || (!array_key_exists($admin_rid, $roles))) {
        drupal_set_message("Roles may be misconfigured. Possible security implications. Ask your administrator to check on this.", "warning");
      }
      else {
        $admin_rolename = $roles[$admin_rid];
      }

      while (list($k, $v)  = each($form['add_roles']['#options'])) {
        if ($v == $admin_rolename) {
          unset($form['add_roles']['#options'][$k]);
        }
      }
      while (list($k, $v)  = each($form['remove_roles']['#options'])) {
        if ($v == $admin_rolename) {
          unset($form['remove_roles']['#options'][$k]);
        }
      }
      break;
  }
}




