<?php
/**
 * @file
 * Code for the Open Berkeley Admin feature.
 */

include_once 'openberkeley_admin.features.inc';
/**
 * Implements hook_menu().
 */
function openberkeley_admin_menu() {

  $items = array();

  $items['admin/config/openberkeley'] = array(
    'title' => 'Open Berkeley',
    'description' => 'Configure Open Berkeley settings.',
    'position' => 'left',
    'weight' => -20,
    'page callback' => 'system_admin_menu_block_page',
    'access callback' => TRUE,
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  return $items;
}

